name: Appium CI
# on push we will trigger our code
on: [push]
env:

  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  API_LEVEL: 33
  ANDROID_BUILD_TOOLS_VERSION: 32.1.14
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis;x86_64
  EMULATOR_TIMEOUT: 550
  EMULATOR_NAME: Pixel 6 API 33

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 #checkout the code 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'oracle'
      
    - name: Set up Node JS 18.16.1
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'
        
    - name: Start Emulator
      run: |
        # Start your emulator with API 33
        # You might use the Android Emulator Runner or similar tools
        # Example:
        emulator -avd Pixel 6 API 33 -no-window
    - name: Install the Emulator
      run: |
         chmod +x ./scripts/RunAppiumServer.sh
         ./scripts/RunAppiumServer.sh  
       
    - name: Run Appium Tests
      run: |
          mvn test
 
       
  
