name: Appium CI
# on push we will trigger our code
on: [push]
env:
  ANDROID_ARCH: x86
  ANDROID_TARGET: google_apis
  API_LEVEL: 29
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0
  ANDROID_SDK_PACKAGES:  system-images;android-29;google_apis;x86 platforms;android-29 build-tools;34.0.0 platform-tools emulator
  EMULATOR_TIMEOUT: 550
  EMULATOR_NAME: test
jobs:
  build:
    runs-on: macos-latest
    strategy: # we are using strategy if we need to run on parallel with different devices and version
     matrix:
       api-level: [29] #29
       target: [google_apis]
    steps:
    - uses: actions/checkout@v3 #checkout the code 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'oracle'
      
    - name: Set up Node JS 18.16.1
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'
        
    - name: Android emulator
      uses: actions/checkout@v3
        
    - name: Add avdmanager and sdkmanager to system PATH
      run: |
            echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH

    - name: Install Sdk
      run: |
           yes Y | sdkmanager --licenses
           sdkmanager --install ${ANDROID_SDK_PACKAGES}
  
    - name: Build emulator
      run: |
       echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
    
  #  - name: Launch emulator
  #    run: |
   #       chmod +x ./scripts/start-emulator.sh
    #      EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./scripts/start-emulator.sh

    - name: Start Emulator
      run: 
         chmod +x ./scripts/start_emulator_1.sh
          ./scripts/start_emulator_1.sh
       
    - name: Install Appium
      run: |
         chmod +x ./scripts/RunAppiumServer.sh
         ./scripts/RunAppiumServer.sh  
         
    - name: Run Appium Tests
      run: |
          mvn test
 
       
  
