name: Appium Tests

on: [push] # You might want to trigger this on various events like push, pull request, etc.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'oracle'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Start Android Emulator
      # Use your own emulator starting commands here
      run: emulator Pixel 6 API 33 -no-audio -no-window &

    - name: Launch emulator
      run: |
          chmod +x ./scripts/start-emulator.sh
          EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./scripts/start-emulator.sh

    - name: Run Appium Tests
      run: mvn -f C:\Projects\testyoutube\pom.xml
