name: Appium CI - macos
# on push we will trigger our code
on: [push]
env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  API_LEVEL: 33
  ANDROID_BUILD_TOOLS_VERSION: 30.0.3
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis;x86_64
  EMULATOR_TIMEOUT: 5000
  EMULATOR_NAME: Pixel_6_API_33_1
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3 #checkout the code 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'oracle'
      
    - name: Set up Node JS 18.16.1
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'

    - name: Install appium
      run: npm install -g appium

    - name: Check appium installation 
      run: appium -v

    - name: Install appium automator
      run: appium driver install uiautomator2
    
    - name: Update  appium automator
      run: appium driver update uiautomator2

    - name: Start appium
      run: appium server --address 127.0.0.1 --port 4723 --use-drivers uiautomator2 --base-path /wd/hub &
      
    - name: Wait for Appium to start
      run: sleep 60 # Adjust the time as needed

    - name: Print Appium status
      run: curl http://127.0.0.1:4723/wd/hub/status

    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
      with:
        api-level: 33
        target: google_apis
        arch: x86_64
        profile: pixel 6
        avd-name: Pixel_6_API_33_1
        script: mvn test --file pom.xml -Dappium.hub=http://127.0.0.1:4723/wd/hub -Dwebdriver.driver=appium -Dappium.platformName=Android -Dappium.deviceName="Pixel_6_API_33_1" -Dcucumber.options="--tags '@ANDROID'"
      
   # - name: Run Appium Tests
    #  run: mvn test --file pom.xml -Dappium.hub=http://127.0.0.1:4723/wd/hub -Dwebdriver.driver=appium -Dappium.platformName=Android -Dappium.deviceName="Pixel_6_API_33_1" -Dcucumber.options="--tags '@ANDROID'"

    - name: Produce report
      run: mvn serenity:aggregate

    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: test-screenshots
        path: artifacts/screenshots

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: target/site
